### ISSUE TITLE
HAPI crawler

### ISSUE THREAD

**Issue by jbfaden** [hapi-server/servers#3]
Bob and I were thinking it would be nice to have some way of aggregating all the labels for datasets in HAPI servers, which clients could use to locate data.  I could write an Autoplot script to go through the known servers, which would create a JSON file containing the dataset identifiers and descriptions.  This file would then be posted here, when changes are detected, so that we could see the history and evolution of the servers, and so there's a known place where clients can search for parameters.  Bob's use case was DST, which might be "dst" on one server and "DST" on another, and it's not even clear who is hosting it.

**Comment by rweigel** [comment]
This is done and the result is https://github.com/hapi-server/servers/tree/master/index

I'll have Srikar convert this to a script that only requires Python.

**Comment by rweigel** [comment]
It seems that this could be done with a ~10-line Python code that uses the Python client. I'll look into this. We should also try to figure out a decent sampleStartDate for datasets that don't have it.
